apiVersion: v1
kind: Pod
metadata:
  name: config
  labels:
    app: apache
spec:
  containers:
  - name: apache
    image: httpd
    ports:
    - containerPort: 80
    volumeMounts:
    - name: mihras
      mountPath: /usr/share/apache2/
  volumes:
  - name: mihras
    configMap:
      name: luffy

